//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  9 2015 22:53:21).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#pragma mark Named Structures

#pragma mark Typedef'd Structures

typedef struct {
    unsigned int _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    double _field14[9];
    double _field15[9];
    float _field16;
    unsigned int _field17;
    _Bool _field18;
    float _field19;
} CDStruct_5a4619cb;
