//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import <objc/NSObject.h>
#import "CDStructures.h"

@interface DeviceGammaContext : NSObject
{
    unsigned int deviceID;
    unsigned int IODisplayService;
    struct __IOHIDServiceClient *frontALSservice;
    struct __IOHIDServiceClient *rearALSservice;
    unsigned int ALS_LMUdataPort;
    struct __CFString *displayContainerID;
    unsigned int numSamples;
    double epsilon;
    double currentWipe;
    double wipeIncrement;
    double updateRate;
    double currentMatrixWipe;
    double wipeMatrixIncrement;
    int internal;
    _Bool hasOverrides;
    _Bool preferencesRead;
    double previousWiperUpdateTimeMS;
    float leakage;
    int lowestLevel;
    float lowestMeasured;
    float maxBacklight;
    float darkReflection;
    float brightReflection;
    double desiredWhitePointXYZ[3];
    double targetWhitePointXYZ[3];
    double targetWhitePointMatrix[9];
    double targetLinearBlack;
    double targetOverGamma;
    _Bool nativeICCvalid;
    double nativeRedXYZ[3];
    double nativeGreenXYZ[3];
    double nativeBlueXYZ[3];
    double nativeWhitePointXYZ[3];
    int whitePointMode;
    double frontALSlux;
    double rearALSlux;
    double backLightNits;
    double linearBacklight;
    dispatch_semaphore_t wiperAnimationRequestSemaphore;
    _Bool animationCompleted;
    _Bool animationPreemptable;
    _Bool animationMatrixCompleted;
    _Bool animationMatrixPreemptive;
    _Bool compensationState;
    struct _opaque_pthread_mutex_t _intentionDictionaryMutex;
    CDStruct_5a4619cb *_nextIntentionDictionary;
    CDStruct_5a4619cb *_previousIntentionDictionary;
    struct _opaque_pthread_mutex_t _prefsIntentionDictionaryMutex;
    CDStruct_5a4619cb *_prefsIntentionDictionary;
    struct _opaque_pthread_mutex_t _timeOfLastAssemblyBufferFlushListMutex;
    _Bool removedState;
    _Bool hardwareBrightnessSmoothing;
    double compositionalWhiteReferenceNits;
    double compositionalAmbientEnvironmentLux;
    int systemGammaMode;
    double staticGamma;
    dispatch_semaphore_t animationSemaphore;
}

- (CDStruct_5a4619cb *)copyPrefsIntentionDictionary;
- (CDStruct_5a4619cb *)copyNextIntentionDictionary;
- (void)setPrefsIntentionDictionary:(CDStruct_5a4619cb *)arg1;
- (void)setIntentionDictionary:(CDStruct_5a4619cb *)arg1;
- (int)getSystemGammaMode;
- (void)setSystemGammaMode:(int)arg1;
- (_Bool)getCompensationState;
- (void)enableCompensation:(_Bool)arg1;
- (_Bool)preferencesRead;
- (void)setpreferencesRead;
- (float)getCompositionalAmbientEnvironmentLux;
- (float)getCompositionalWhiteReferenceNits;
- (void)fetchAndSetCompositionalEnvironementOnce;
- (void)readDisplayOverrides:(unsigned int)arg1;
- (_Bool)overridesFound;
- (void)setOverridesFound:(_Bool)arg1;
- (_Bool)animationMatrixPreemptive;
- (_Bool)animationMatrixCompleted;
- (_Bool)animationPreemptable;
- (_Bool)animationCompleted;
- (float)getALSluxWithLocation:(int)arg1;
- (void)setALSlux:(double)arg1 withALSlocation:(int)arg2;
- (float)getDarkReflectivity;
- (float)getDarkReflection;
- (_Bool)getHardwareBrightnessSmoothingState;
- (_Bool)getRemovedState;
- (void)setRemovedState:(_Bool)arg1;
- (void)updateDisplayHasBrightnessSmoothing;
- (void)updateDisplayIsInternal;
- (void)pollAndupdateBacklightNits;
- (void)pollAndUpdateALSlux;
- (void)setBackLightNits:(double)arg1 withLinearBacklight:(double)arg2;
- (float)getBackLightLux;
- (float)getLinearBacklight;
- (float)getBackLightNits;
- (void)setMaxBackLight:(double)arg1;
- (float)getMaxBackLightNits;
- (float)getFullBacklightLeakageNits;
- (int)getLowestLevel;
- (double *)copyTargetWhitePointMatrix;
- (void)setTargetWhitePointMatrix:(double *)arg1;
- (int)getWhitePointMode;
- (void)setWhitePointMode:(int)arg1;
- (double)getTargetOverGamma;
- (void)setTargetOverGamma:(double)arg1;
- (double)getTargetLinearBlackpoint;
- (void)setTargetLinearBlackpoint:(double)arg1;
- (void)setTargetWhitePointXYZ:(double *)arg1;
- (double *)getTargetWhitePointXYZ;
- (void)setDesiredWhitePointXYZ:(double *)arg1;
- (double *)getDesiredWhitePointXYZ;
- (void)queryAndSetIntentionForWhitePoint;
- (_Bool)createNativeColorSpaceVectorsWithRedXYZ:(double **)arg1 greenXYZ:(double **)arg2 blueXYZ:(double **)arg3 whitePointXYZ:(double **)arg4;
- (double *)createNativeWhitePointVector;
- (_Bool)cacheColorSpaceFromICC;
- (float)getStaticGamma;
- (void)setStaticGamma:(float)arg1;
- (void)setAndAnimateToGamma:(float)arg1 thawIntention:(_Bool)arg2;
- (void)setNativeWhitePointAndAnimateWithDuration:(float)arg1 thawIntention:(_Bool)arg2;
- (void)setWhitePointXYZandAnimateToX:(float)arg1 Y:(float)arg2 Z:(float)arg3 duration:(float)arg4 thawIntention:(_Bool)arg5;
- (void)setDisplayParametersWithLeakage:(float)arg1 lowestLevel:(int)arg2 lowestMeasured:(float)arg3 backlight:(float)arg4 darkReflection:(float)arg5 brightReflection:(float)arg6;
- (void)registerHIDservices;
- (void)setInternal:(BOOL)arg1;
- (BOOL)isInternal;
- (BOOL)isNativeICCvalidOrRetry;
- (struct __CFString *)getDisplayContainerID;
- (void)invalidateALSservices;
- (_Bool)frontALSserviceValid;
- (void)setRearALSservice:(struct __IOHIDServiceClient *)arg1;
- (void)setFrontALSservice:(struct __IOHIDServiceClient *)arg1;
- (unsigned int)getIODisplayService;
- (void)setDisplayID:(unsigned int)arg1;
- (unsigned int)getDisplayID;
- (double)updateWipeWithActualIntervalInSeconds:(float)arg1;
- (void)setupInterpolationWithDuration:(double)arg1 withUpdateRateFPS:(double)arg2 direction:(unsigned char)arg3;
- (void)interpolateCurrentTableToDestinationTableOverTime:(float)arg1 withUpdateRatePerSecond:(float)arg2 withPreemption:(BOOL)arg3;
- (double)getCurrentAttenuation;
- (void)releaseAnimationLock;
- (int)requestAndWaitForAnimationToEndNonLocking;
- (int)requestAndWaitForAnimationToEndLocking;
- (int)waitForAnimationToEndLocking;
- (void)signalAnimationToEnd;
- (void)resetAnimationSemaphore;
- (_Bool)preemptableAnimationSleepSeconds:(double)arg1;
- (void)dealloc;
- (id)initWithCount:(int)arg1 withDisplayID:(unsigned int)arg2;

@end

