//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct _CGSDisplayModeDescription {
    int displayModeNumber;
    int flags;
    int width;
    int height;
    int depth;
    int rowBytes;
    int bitsPerPixel;
    int bitsPerSample;
    int samplesPerPixel;
    int refreshRate;
    int horizontalResolution;
    int verticalResolution;
    char encoding[129];
    int version;
    int length;
    int fixPtRefreshRate;
    int ioModeInfoFlags;
    int ioDisplayModeNumber;
    int pixelsWide;
    int pixelsHigh;
    float resolution;
};

