//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle, NSView;

@interface MonitorPanel : NSObject
{
    int _displayID;
    NSBundle *_bundle;
    NSView *_view;
    id _controller;
}

+ (int)fidelityForDisplayID:(int)arg1;
- (void)setController:(id)arg1;
- (id)controller;
- (void)setBundle:(id)arg1;
- (id)bundle;
- (void)didChangeScreenParameters;
- (void)displayHardwareChanged;
- (void)displayDidReconfigure;
- (void)displayWillReconfigure;
- (void)didSelect;
- (void)willSelect;
- (void)didUnselect;
- (void)willUnselect;
- (BOOL)shouldUnselect;
- (id)nibName;
- (unsigned int)type;
- (unsigned int)family;
- (int)minorOrder;
- (int)majorOrder;
- (id)view;
- (void)didLoadNib;
- (void)dealloc;
- (id)initWithDisplayID:(int)arg1;

@end

